name: Build Android APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Bubblewrap
        run: npm install -g @bubblewrap/cli

      - name: Build TWA App
        run: |
          yes | bubblewrap init --manifest=https://medhoms2028.netlify.app/manifest.json
          bubblewrap build --accept_toast_navigation_parameters
